### ISSUE TITLE
Consoles cores = runtime error: stack empty

### ISSUE THREAD

**Issue by birdybro** [paulofmandown/mister-discord-rpc#1]
Arcade cores work fine, but console cores don't work.

```
C:\Users\aberu\Downloads\MiSTerDiscordRpc>MiSTerDiscordRPC.exe
What is the MiSTer's Address?
192.168.0.130
Sending new presence: Playing  on menu
Sending new presence: Playing 1943 Kai Midway Kaisen on jt1943
Runtime error: Stack empty.
```
I did menu, then 1943, then Genesis. SNES and TGFX16 do the same thing.

**Comment by paulofmandown** [comment]
That's a weird error. Do you have [recents enabled in MiSTer.ini](https://github.com/MiSTer-devel/Main_MiSTer/wiki/Configuration-Files#recents)?

**Comment by birdybro** [comment]
Recents is disabled, but I just noticed something weird about my ini, but will have to check after work today... I'll get back to you on this.

**Comment by paulofmandown** [comment]
Found something that should prevent that specific error from being thrown, but I'm pretty confident that it won't get console cores working for you

https://github.com/paulofmandown/mister-discord-rpc/releases/tag/v1.0.1

**Comment by birdybro** [comment]
Thank you! I'll try it out again sometime. I actually had a few things up. For some reason vs-code switched back to the wrong line endings, so some files that i edited in my code editor had improper line endings, and i think this was causing some errors. Sorry about the trouble.
